name: Release
on:
  push:
    branches:
      - release

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [
          macos-latest,
          # ubuntu-20.04,
          windows-latest
        ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install front dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseName: v__VERSION__
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false

  update:
    needs: release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install front dependencies
        run: pnpm install

      - name: Update update.json
        run: node ./.github/scripts/github-update.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
